
# wandb:
user: condinv-ssl # judyye
api: 8e99ff14eba9677d715999d7a282c9ff79cfb9bf # 8e99ff14eba9677d715999d7a282c9ff79cfb9bf

remote_str: /private/home/yufeiy2/scratch/
data_dir: ${environment.remote_str}/result/
output: ${environment.remote_str}/result/homan

submitit_dir: ${exp_dir}/submitit_train_logs/


# world_size: 1
# rank: 0
# dist_url: tcp://localhost:10001
# dist_backend: nccl
# port: 10001
# node: localhost


# multiprocessing_distributed: False
# distributed: True
# seed:
# workers: 40
# mem_gb: 256
# gpu_mem_gb: '20G'


